export component Button{
    in property <string> text: "button";
    in property <brush> background: @linear-gradient(-45deg,#27acb8,#3b5be7);
    height: 50px;

    Rectangle {
        background: ta.pressed? @linear-gradient(45deg,#27acb8,#3b5be7): ta.has-hover ? background.darker(5%) : background;
        animate background { duration:100ms; }
        border-radius: 8px;
        ta:= TouchArea{
            clicked => {
                // 为发现如何修改指定的方法
            }
        }
        padding: 10px;
    }
    Text {text: root.text; font-size: 14px;}

}
