export component Button{
    in property <string> title: "button";
    in property <brush> background: @linear-gradient(-45deg,#27acb8,#3b5be7);
    callback clicked;

    height: 50px;

    Rectangle {
        background: ta.pressed? @linear-gradient(45deg,#27acb8,#3b5be7): ta.has-hover ? background.darker(5%) : background;
        animate background { duration:100ms; }
        border-radius: 8px;
        ta:= TouchArea{
            clicked => { 
                root.clicked() 
            }
        }
        padding: 10px;
    }
    Text {text: root.title; font-size: 14px;}
}
