import { HorizontalBox } from "std-widgets.slint";
export component Page inherits Rectangle {
    in property <string> header: "默认文本";

    in property <bool> night-mode: false;

    background: #3facac;
    callback back;
    VerticalLayout {
        alignment: start;
        padding-top: i.height * 0.55;
        HorizontalLayout {
            spacing: i.width;
            padding-left: i.width;
            i := Image {
                y: (h.height - self.height) / 2;
                source: @image-url("img/back.svg");
                image-fit: contain;
                colorize: #6284FF;
                width: 18px;
                height: 24px;

                TouchArea {
                    clicked => {
                        root.back()
                    }
                    x: 0;
                    width: 150%;
                }
            }

            h := Text {
                text: header;
                font-weight: 900;
                font-size: 16px * 2;
                color: root.night-mode ? #12298f : #011316;
            }
        }

        // protect underneath controls
        TouchArea { }

        @children
    }
}
